### PR TITLE
Added DNS configuration functionality.

### PR DESCRIPTION
**Pull request by Revertron**
Fixes https://github.com/yggdrasil-network/yggdrasil-android/issues/9.

I've added three my servers in Yggdrasil as default servers. They resolve regular ICANN domains, ALFIS, and OpenNIC. And they also block advertisement, counters and malware domains (just the basic lists of AdGuard Home, nothing very intrusive). These servers proved to be the most stable of all in our community :)

Anyone can delete any of them and set any servers as they like. But having something working as default makes it easier to get onboard.

P.S.: And added some micro changes in UI here and there.

### CODE REVIEW

**Review by neilalexander — COMMENTED** [review]
On the whole I don't think I want to encourage overwriting the default DNS servers out-of-the-box, as it may be surprising to users and possibly cause future problems with app review.

Can we perhaps add a button instead, labelled something like "Use Alfis DNS servers", which replaces the DNS config to these hard-coded addresses instead?

**Comment by Revertron** [comment]
Yep, that's a good idea. Need to think how it would be better to implement in UI...

**Comment by Revertron** [comment]
Fixed the UI.
Now it look like this:

image

**Review by neilalexander — APPROVED** [review]
Currently it's possible to tap the `+` button on one of the prepopulated DNS servers more than once, so we may want to make it so that we can't add the same DNS server multiple times.

Beyond that, this looks great and I'm happy for the duplicate issue to be addressed in a separate PR.

**Pull request merged**
