### PR TITLE
Update core library and tag new version 0.1-016

### PR DESCRIPTION
**Pull request by basilgello**
- Bump yggdrasil-go submodule to 0.5.4
- Fix VPN connection not closed on Yggdrasil switch toggled off
- Version 0.1-016

### CODE REVIEW

**Review by neilalexander — APPROVED** [review]
In principle LGTM, but I don't think updating the submodule does anything as I think CI always checks out `develop`.

**Comment by basilgello** [comment]
CI yes but F-Droid might think different :)

**Comment by basilgello** [comment]
Also fixed VPN connection not destroyed on switch off.

**Comment by Revertron** [comment]
We need to merge https://github.com/yggdrasil-network/yggdrasil-android/pull/54 before this.

**Review by Revertron — APPROVED** [review]
LGTM too, let's merge.

**Comment by basilgello** [comment]
Great! And new tag :)

**Comment by Revertron** [comment]
> Great! And new tag :)

Done! :)

**Pull request merged**
